/** Check for keys pressed by like: Key.isUpArrow(e) */
namespace Key {
  export function isBackspace(e: KeyboardEvent) { return (e.keyCode == 8); }
  export function isTab(e: KeyboardEvent) { return (e.keyCode == 9); }
  export function isEnter(e: KeyboardEvent) { return (e.keyCode == 13); }
  /** alternative: if (e.shiftKey && Key.isUpArrow(e)) */
  export function isShift(e: KeyboardEvent) { return (e.keyCode == 16); }
  /** alternative: if (e.ctrlKey && Key.isUpArrow(e)) */
  export function isCtrl(e: KeyboardEvent) { return (e.keyCode == 17); }
  /** alternative: if (e.altKey && Key.isUpArrow(e)) */
  export function isAlt(e: KeyboardEvent) { return (e.keyCode == 18); }
  export function isPauseBreak(e: KeyboardEvent) { return (e.keyCode == 19); }
  export function isCapsLock(e: KeyboardEvent) { return (e.keyCode == 20); }
  export function isEscape(e: KeyboardEvent) { return (e.keyCode == 27); }
  export function isPageUp(e: KeyboardEvent) { return (e.keyCode == 33); }
  export function isPageDown(e: KeyboardEvent) { return (e.keyCode == 34); }
  export function isEnd(e: KeyboardEvent) { return (e.keyCode == 35); }
  export function isHome(e: KeyboardEvent) { return (e.keyCode == 36); }
  export function isLeftArrow(e: KeyboardEvent) { return (e.keyCode == 37); }
  export function isUpArrow(e: KeyboardEvent) { return (e.keyCode == 38); }
  export function isRightArrow(e: KeyboardEvent) { return (e.keyCode == 39); }
  export function isDownArrow(e: KeyboardEvent) { return (e.keyCode == 40); }
  export function isInsert(e: KeyboardEvent) { return (e.keyCode == 45); }
  export function isDelete(e: KeyboardEvent) { return (e.keyCode == 46); }
  export function is0(e: KeyboardEvent) { return (e.keyCode == 48); }
  export function is1(e: KeyboardEvent) { return (e.keyCode == 49); }
  export function is2(e: KeyboardEvent) { return (e.keyCode == 50); }
  export function is3(e: KeyboardEvent) { return (e.keyCode == 51); }
  export function is4(e: KeyboardEvent) { return (e.keyCode == 52); }
  export function is5(e: KeyboardEvent) { return (e.keyCode == 53); }
  export function is6(e: KeyboardEvent) { return (e.keyCode == 54); }
  export function is7(e: KeyboardEvent) { return (e.keyCode == 55); }
  export function is8(e: KeyboardEvent) { return (e.keyCode == 56); }
  export function is9(e: KeyboardEvent) { return (e.keyCode == 57); }
  export function isA(e: KeyboardEvent) { return (e.keyCode == 65); }
  export function isB(e: KeyboardEvent) { return (e.keyCode == 66); }
  export function isC(e: KeyboardEvent) { return (e.keyCode == 67); }
  export function isD(e: KeyboardEvent) { return (e.keyCode == 68); }
  export function isE(e: KeyboardEvent) { return (e.keyCode == 69); }
  export function isF(e: KeyboardEvent) { return (e.keyCode == 70); }
  export function isG(e: KeyboardEvent) { return (e.keyCode == 71); }
  export function isH(e: KeyboardEvent) { return (e.keyCode == 72); }
  export function isI(e: KeyboardEvent) { return (e.keyCode == 73); }
  export function isJ(e: KeyboardEvent) { return (e.keyCode == 74); }
  export function isK(e: KeyboardEvent) { return (e.keyCode == 75); }
  export function isL(e: KeyboardEvent) { return (e.keyCode == 76); }
  export function isM(e: KeyboardEvent) { return (e.keyCode == 77); }
  export function isN(e: KeyboardEvent) { return (e.keyCode == 78); }
  export function isO(e: KeyboardEvent) { return (e.keyCode == 79); }
  export function isP(e: KeyboardEvent) { return (e.keyCode == 80); }
  export function isQ(e: KeyboardEvent) { return (e.keyCode == 81); }
  export function isR(e: KeyboardEvent) { return (e.keyCode == 82); }
  export function isS(e: KeyboardEvent) { return (e.keyCode == 83); }
  export function isT(e: KeyboardEvent) { return (e.keyCode == 84); }
  export function isU(e: KeyboardEvent) { return (e.keyCode == 85); }
  export function isV(e: KeyboardEvent) { return (e.keyCode == 86); }
  export function isW(e: KeyboardEvent) { return (e.keyCode == 87); }
  export function isX(e: KeyboardEvent) { return (e.keyCode == 88); }
  export function isY(e: KeyboardEvent) { return (e.keyCode == 89); }
  export function isZ(e: KeyboardEvent) { return (e.keyCode == 90); }
  export function isLeftWindowKey(e: KeyboardEvent) { return (e.keyCode == 91); }
  export function isRightWindowKey(e: KeyboardEvent) { return (e.keyCode == 92); }
  export function isSelectKey(e: KeyboardEvent) { return (e.keyCode == 93); }
  export function isNumpad0(e: KeyboardEvent) { return (e.keyCode == 96); }
  export function isNumpad1(e: KeyboardEvent) { return (e.keyCode == 97); }
  export function isNumpad2(e: KeyboardEvent) { return (e.keyCode == 98); }
  export function isNumpad3(e: KeyboardEvent) { return (e.keyCode == 99); }
  export function isNumpad4(e: KeyboardEvent) { return (e.keyCode == 100); }
  export function isNumpad5(e: KeyboardEvent) { return (e.keyCode == 101); }
  export function isNumpad6(e: KeyboardEvent) { return (e.keyCode == 102); }
  export function isNumpad7(e: KeyboardEvent) { return (e.keyCode == 103); }
  export function isNumpad8(e: KeyboardEvent) { return (e.keyCode == 104); }
  export function isNumpad9(e: KeyboardEvent) { return (e.keyCode == 105); }
  export function isMultiply(e: KeyboardEvent) { return (e.keyCode == 106); }
  export function isAdd(e: KeyboardEvent) { return (e.keyCode == 107); }
  export function isSubtract(e: KeyboardEvent) { return (e.keyCode == 109); }
  export function isDecimalPoint(e: KeyboardEvent) { return (e.keyCode == 110); }
  export function isDivide(e: KeyboardEvent) { return (e.keyCode == 111); }
  export function isF1(e: KeyboardEvent) { return (e.keyCode == 112); }
  export function isF2(e: KeyboardEvent) { return (e.keyCode == 113); }
  export function isF3(e: KeyboardEvent) { return (e.keyCode == 114); }
  export function isF4(e: KeyboardEvent) { return (e.keyCode == 115); }
  export function isF5(e: KeyboardEvent) { return (e.keyCode == 116); }
  export function isF6(e: KeyboardEvent) { return (e.keyCode == 117); }
  export function isF7(e: KeyboardEvent) { return (e.keyCode == 118); }
  export function isF8(e: KeyboardEvent) { return (e.keyCode == 119); }
  export function isF9(e: KeyboardEvent) { return (e.keyCode == 120); }
  export function isF10(e: KeyboardEvent) { return (e.keyCode == 121); }
  export function isF11(e: KeyboardEvent) { return (e.keyCode == 122); }
  export function isF12(e: KeyboardEvent) { return (e.keyCode == 123); }
  export function isNumLock(e: KeyboardEvent) { return (e.keyCode == 144); }
  export function isScrollLock(e: KeyboardEvent) { return (e.keyCode == 145); }
  export function isSemicolon(e: KeyboardEvent) { return (e.keyCode == 186); }
  export function isEqualSign(e: KeyboardEvent) { return (e.keyCode == 187); }
  export function isComma(e: KeyboardEvent) { return (e.keyCode == 188); }
  export function isDash(e: KeyboardEvent) { return (e.keyCode == 189); }
  export function isPeriod(e: KeyboardEvent) { return (e.keyCode == 190); }
  export function isForwardSlash(e: KeyboardEvent) { return (e.keyCode == 191); }
  export function isGraveAccent(e: KeyboardEvent) { return (e.keyCode == 192); }
  export function isOpenBracket(e: KeyboardEvent) { return (e.keyCode == 219); }
  export function isBackSlash(e: KeyboardEvent) { return (e.keyCode == 220); }
  export function isCloseBraket(e: KeyboardEvent) { return (e.keyCode == 221); }
  export function isSingleQuote(e: KeyboardEvent) { return (e.keyCode == 222); }
}
